<a href="https://colab.research.google.com/github/Sudeeppp-Mishra/Machine-Learning-101/blob/main/Lab-Works/Lab-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with Dictionary and DataFrame

## Part I: Working with Dictionary
- A data structure used to store data in **key-value pairs**

```python
student = {
  "name" : "Hari",
  "age" : 20,
  "faculty": "BCE"
}
```

Tasks: Perform following operations

## Create Dictionary -> d = {}

In [ ]:
student = {
  "name" : "Hari",
  "age" : 20,
  "faculty": "BCE"
}

## Access Value -> d[key]

In [ ]:
print(student["name"])

Hari

## Using get() -> d.get(key)

In [ ]:
print(student.get("age"))

20

## Adding Item -> d[key] = value

In [ ]:
student['group'] = 'B'
print(student)

{'name': 'Hari', 'age': 20, 'faculty': 'BCE', 'group': 'B'}

## Update Vlue -> d[key] = new value

In [ ]:
student['name'] = 'Shyam'
print(student)

{'name': 'Shyam', 'age': 20, 'faculty': 'BCE', 'group': 'B'}

## Remove Item using del -> del d[key]

In [ ]:
del student['group']
print(student)

{'name': 'Shyam', 'age': 20, 'faculty': 'BCE'}

## Remove using pop -> d.pop(key)

In [ ]:
student.pop("name")

'Shyam'

In [ ]:
print(student)

{'age': 20, 'faculty': 'BCE'}

## Remove Last Item -> d.popitem()

In [ ]:
student.popitem()

('faculty', 'BCE')

In [ ]:
print(student)

{'age': 20}

## Clear dictionary -> d.clear()

In [ ]:
student.clear()
print(student)

{}

## Copy Dictionary -> d.copy()

In [ ]:
student = {
  "name" : "Hari",
  "age" : 20,
  "faculty": "BCE"
}

student_copy = student.copy()
print(student_copy)

{'name': 'Hari', 'age': 20, 'faculty': 'BCE'}

## Get all keys -> d.keys()

In [ ]:
print(student.keys())

dict_keys(['name', 'age', 'faculty'])

## Get all values -> d.values()

In [ ]:
print(student.values())

dict_values(['Hari', 20, 'BCE'])

## Get all items -> d.items()

In [ ]:
print(student.items())

dict_items([('name', 'Hari'), ('age', 20), ('faculty', 'BCE')])

## Check Key Exits -> key in d

In [ ]:
'name' in student

True

## Get Length -> len(d)

In [ ]:
len(student)

3

## Loop Through Keys -> for k in d:

In [ ]:
for keys in student:
  print(keys)
  print(student[keys])

name
Hari
age
20
faculty
BCE

## Loop Through Values -> for v in d.values():

In [ ]:
for values in student.values():
  print(values)

Hari
20
BCE

Loop Through Items -> for k, v in d.items():

In [ ]:
for keys, values in student.items():
  print(keys, values)

name Hari
age 20
faculty BCE

## Part II: Working with Pandas DataFrame

In [ ]:
import pandas as pd

data = {
    'Name': ['Ram', 'Shyam', 'Hari', 'Sita', 'Gita', 'Pdf'],
    'Age': [24, 27, 22, 32, 20, 22],
    'City': ['Kathmandu', 'Bhaktapur', 'Bajhang', 'Lalitpur', 'Biratnagar', 'idk'],
    'Marks': [14, 77, 62, 32, 80, 92]
}

## Creating a DataFrame -> df.= pd.DataFrame()

In [ ]:
df = pd.DataFrame(data)

## Displaying the first 5 rows of the DataFrame -> df.head()

In [ ]:
df.to_csv('my_dataframe.csv', index=False)
print('DataFrame saved to my_dataframe.csv')

    Name  Age        City  Marks
0    Ram   24   Kathmandu     14
1  Shyam   27   Bhaktapur     77
2   Hari   22     Bajhang     62
3   Sita   32    Lalitpur     32
4   Gita   20  Biratnagar     80

## Displaying the last 5 rows of the DataFrame -> df.tail()

In [ ]:
df.tail()

    Name  Age        City  Marks
1  Shyam   27   Bhaktapur     77
2   Hari   22     Bajhang     62
3   Sita   32    Lalitpur     32
4   Gita   20  Biratnagar     80
5    Pdf   22         idk     92

## Find the total no. of rows and columns in the DataFrame -> df.shape

In [ ]:
print(df.shape)

(6, 4)

## Display all column names in the DataFrame -> df.columns

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

## Display complete info. about the DataFrame including data types and memory usuage -> df.info()

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Marks   6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes
None

## Generate a statistical summary of numerical columns in the DataFrame -> df.describe()

In [ ]:
print(df.describe())

             Age      Marks
count   6.000000   6.000000
mean   24.500000  59.500000
std     4.370355  30.382561
min    20.000000  14.000000
25%    22.000000  39.500000
50%    23.000000  69.500000
75%    26.250000  79.250000
max    32.000000  92.000000

## Select and display the Name column from the DataFrame -> df['Name']

In [ ]:
print(df['Name'])

0      Ram
1    Shyam
2     Hari
3     Sita
4     Gita
5      Pdf
Name: Name, dtype: object

## Select and display multiple columns such as Name and Age -> df[['Name', 'Age']]

In [ ]:
print(df[['Name', 'Age']])

    Name  Age
0    Ram   24
1  Shyam   27
2   Hari   22
3   Sita   32
4   Gita   20
5    Pdf   22

## Display the first row of the DataFrame using positional indexing -> df.iloc[0]

In [ ]:
print(df.iloc[0])

Name           Ram
Age             24
City     Kathmandu
Marks           14
Name: 0, dtype: object

## Display the first row of the DataFrame using label-based indexing -> df.loc[0]

In [ ]:
print(df.loc[0])

Name           Ram
Age             24
City     Kathmandu
Marks           14
Name: 0, dtype: object

## Access a specific cell value such as Age of the first student -> df.loc[0, 'Age']

In [ ]:
print(df.loc[0, 'Age'])

24

## Filter and display students whose age are greater than 20 -> df[df['Age']>20]

In [ ]:
print(df[df['Age']>20])

    Name  Age       City  Marks
0    Ram   24  Kathmandu     14
1  Shyam   27  Bhaktapur     77
2   Hari   22    Bajhang     62
3   Sita   32   Lalitpur     32
5    Pdf   22        idk     92

## Filter and display students whose Age is gereater than 20 and Marks is greater than 80 -> df[(df['Age']>20)&(df['Marks']>80)]

In [ ]:
print(df[(df['Age']>20)&(df['Marks']>80)])

  Name  Age City  Marks
5  Pdf   22  idk     92

## Add a new column called Grade to the DataFrame -> df['Grade'] = ['A', 'B']

In [ ]:
df['Grade'] = ['A', 'B-', 'A-', 'B+', 'C', 'A']
print(df)

    Name  Age        City  Marks Grade
0    Ram   24   Kathmandu     14     A
1  Shyam   27   Bhaktapur     77    B-
2   Hari   22     Bajhang     62    A-
3   Sita   32    Lalitpur     32    B+
4   Gita   20  Biratnagar     80     C
5    Pdf   22         idk     92     A

## Increase all students Marks by 5 -> df['Marks'] = df['Marks']+5

In [ ]:
df['Marks'] = df['Marks']+5
print(df)

    Name  Age        City  Marks Grade
0    Ram   24   Kathmandu     19     A
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+
4   Gita   20  Biratnagar     85     C
5    Pdf   22         idk     97     A

## Update the Marks of Ram to 95 using a condition -> df.loc[df['Name'] == 'Ram', 'Marks'] = 95

In [ ]:
df.loc[df['Name'] == 'Ram', 'Marks'] = 95
print(df)

    Name  Age        City  Marks Grade
0    Ram   24   Kathmandu     95     A
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+
4   Gita   20  Biratnagar     85     C
5    Pdf   22         idk     97     A

## Remove the Age column from the DataFrame -> df.drop('Age', axis=1)

In [ ]:
print(df.drop('Age', axis=1))

    Name        City  Marks Grade
0    Ram   Kathmandu     95     A
1  Shyam   Bhaktapur     82    B-
2   Hari     Bajhang     67    A-
3   Sita    Lalitpur     37    B+
4   Gita  Biratnagar     85     C
5    Pdf         idk     97     A

## Remove the first row from the DataFrame -> df.drop(0, axis=0)

In [ ]:
print(df.drop(0, axis=0))

    Name  Age        City  Marks Grade
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+
4   Gita   20  Biratnagar     85     C
5    Pdf   22         idk     97     A

## Sort the DataFrame by Marks in ascending order -> df.sort_values('Marks')

In [ ]:
sorted_df = df.sort_values('Marks')
print(sorted_df)

    Name  Age        City  Marks Grade
3   Sita   32    Lalitpur     37    B+
2   Hari   22     Bajhang     67    A-
1  Shyam   27   Bhaktapur     82    B-
4   Gita   20  Biratnagar     85     C
0    Ram   24   Kathmandu     95     A
5    Pdf   22         idk     97     A

## Sort the Dataframe by Marks in descending order -> df.sort_values('Marks', ascending = False)

In [ ]:
sorted_desc_df = df.sort_values('Marks', ascending = False)
print(sorted_desc_df)

    Name  Age        City  Marks Grade
5    Pdf   22         idk     97     A
0    Ram   24   Kathmandu     95     A
4   Gita   20  Biratnagar     85     C
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+

## Concatenate two DataFrames vertically -> pd.concat([df1, df2])

In [ ]:
data1 = {
    'Name': ['Ram', 'Shyam', 'Hari'],
    'Age': [24, 27, 22],
    'City': ['Kathmandu', 'Bhaktapur', 'Lalitpur']
}
data2 = {
    'Name': ['Sita', 'Gita', 'Rita'],
    'Age': [21, 21, 22],
    'City': ['Bajhang', 'Bajura', 'Doti']
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print('<-----------df1----------->')
print(df1)
print('<-----------df2----------->')
print(df2)

concatenated_df = pd.concat([df1, df2])
print('<------------concatenated df---------->')
print(concatenated_df)

<-----------df1----------->
    Name  Age       City
0    Ram   24  Kathmandu
1  Shyam   27  Bhaktapur
2   Hari   22   Lalitpur
<-----------df2----------->
   Name  Age     City
0  Sita   21  Bajhang
1  Gita   21   Bajura
2  Rita   22     Doti
<------------concatenated df---------->
    Name  Age       City
0    Ram   24  Kathmandu
1  Shyam   27  Bhaktapur
2   Hari   22   Lalitpur
0   Sita   21    Bajhang
1   Gita   21     Bajura
2   Rita   22       Doti

## Read data from a CSV file into a DataFrame -> pd.read_csv('file.csv')

In [ ]:
pd.read_csv('data.csv')

     Name   Age   Marks  Grade
0     Ram    18      88   "A-"
1  Sworup    90      99    "A"
2  Sangat   150      99    "A"
3     pdf    22     100    "A"

## Write the DataFrame into a CSV file -> df.to_csv('file.csv')

In [ ]:
df.to_csv('file.csv')
pd.read_csv('file.csv')

   Unnamed: 0   Name  Age        City  Marks Grade
0           0    Ram   24   Kathmandu     95     A
1           1  Shyam   27   Bhaktapur     82    B-
2           2   Hari   22     Bajhang     67    A-
3           3   Sita   32    Lalitpur     37    B+
4           4   Gita   20  Biratnagar     85     C
5           5    Pdf   22         idk     97     A

## Write the DataFrame into an Excel file -> df.to_excel('file.xslx')

In [ ]:
# 1. Create the student data
student_data = {
    'Name': ['Ram', 'Shyam', 'Sita', 'Gita'],
    'Age': [21, 22, 20, 21],
    'Marks': [85, 92, 78, 95],
    'Grade': ['A', 'A+', 'B', 'A+']
}

# 2. Convert to a DataFrame
df = pd.DataFrame(student_data)

# 3. Export to an Excel (.xlsx) file
# Note: index=False prevents Pandas from adding a row-number column
df.to_excel('students_report.xlsx', index=False)

print("Excel file '.xlsx' created successfully!")

Excel file '.xlsx' created successfully!

## Read data from an Excel file into a DataFrame -> pd.read_excel('file.xlsx')

In [ ]:
pd.read_excel('students_report.xlsx')

    Name  Age  Marks Grade
0    Ram   21     85     A
1  Shyam   22     92    A+
2   Sita   20     78     B
3   Gita   21     95    A+